//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration control window.
        /// </summary>
        internal static string adminWelcome {
            get {
                return ResourceManager.GetString("adminWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string annotation {
            get {
                return ResourceManager.GetString("annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string birth {
            get {
                return ResourceManager.GetString("birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book examples.
        /// </summary>
        internal static string bookLibExample {
            get {
                return ResourceManager.GetString("bookLibExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of books on client hands.
        /// </summary>
        internal static string bookList {
            get {
                return ResourceManager.GetString("bookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory book number.
        /// </summary>
        internal static string bookNum {
            get {
                return ResourceManager.GetString("bookNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client information.
        /// </summary>
        internal static string clientCreate {
            get {
                return ResourceManager.GetString("clientCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client information.
        /// </summary>
        internal static string clientEdit {
            get {
                return ResourceManager.GetString("clientEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create book information.
        /// </summary>
        internal static string createBook {
            get {
                return ResourceManager.GetString("createBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new client.
        /// </summary>
        internal static string createClient {
            get {
                return ResourceManager.GetString("createClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do wou want to delete selected.
        /// </summary>
        internal static string deleteConfirm {
            get {
                return ResourceManager.GetString("deleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book information.
        /// </summary>
        internal static string editBook {
            get {
                return ResourceManager.GetString("editBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window of change information about readers.
        /// </summary>
        internal static string editReaderInfo {
            get {
                return ResourceManager.GetString("editReaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window of change information about users.
        /// </summary>
        internal static string editUserInfo {
            get {
                return ResourceManager.GetString("editUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Login&quot; should not be empty.
        /// </summary>
        internal static string errorLoginEmpty {
            get {
                return ResourceManager.GetString("errorLoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Password&quot; should not be empty.
        /// </summary>
        internal static string errorPasswordEmpty {
            get {
                return ResourceManager.GetString("errorPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full title.
        /// </summary>
        internal static string fullTitle {
            get {
                return ResourceManager.GetString("fullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return book to library.
        /// </summary>
        internal static string getBook {
            get {
                return ResourceManager.GetString("getBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give book to reader.
        /// </summary>
        internal static string giveBook {
            get {
                return ResourceManager.GetString("giveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string importantFieldMark {
            get {
                return ResourceManager.GetString("importantFieldMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Code.
        /// </summary>
        internal static string inventoryCode {
            get {
                return ResourceManager.GetString("inventoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory code modify window.
        /// </summary>
        internal static string inventoryCodeWelcome {
            get {
                return ResourceManager.GetString("inventoryCodeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN code.
        /// </summary>
        internal static string isbn {
            get {
                return ResourceManager.GetString("isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian.
        /// </summary>
        internal static string librarian {
            get {
                return ResourceManager.GetString("librarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian management window.
        /// </summary>
        internal static string librarianWelcome {
            get {
                return ResourceManager.GetString("librarianWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library number ticket.
        /// </summary>
        internal static string libraryNumTicket {
            get {
                return ResourceManager.GetString("libraryNumTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inventory numbers for current isbn.
        /// </summary>
        internal static string listBookNum {
            get {
                return ResourceManager.GetString("listBookNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        internal static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on failed.
        /// </summary>
        internal static string logonFailed {
            get {
                return ResourceManager.GetString("logonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book information.
        /// </summary>
        internal static string manageBook {
            get {
                return ResourceManager.GetString("manageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        internal static string manageUser {
            get {
                return ResourceManager.GetString("manageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During processing your operation something went wrong.
        /// </summary>
        internal static string operationNOK {
            get {
                return ResourceManager.GetString("operationNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successfully done.
        /// </summary>
        internal static string operationOK {
            get {
                return ResourceManager.GetString("operationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Subject.
        /// </summary>
        internal static string parentSubject {
            get {
                return ResourceManager.GetString("parentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View personal client information.
        /// </summary>
        internal static string personalInfo {
            get {
                return ResourceManager.GetString("personalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone: +380.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string publishDate {
            get {
                return ResourceManager.GetString("publishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish House.
        /// </summary>
        internal static string publishHouse {
            get {
                return ResourceManager.GetString("publishHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        internal static string publishHouseName {
            get {
                return ResourceManager.GetString("publishHouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent book on user hand.
        /// </summary>
        internal static string rentBook {
            get {
                return ResourceManager.GetString("rentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return book.
        /// </summary>
        internal static string returnBook {
            get {
                return ResourceManager.GetString("returnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing house with this name is not exist in library. Do you want to add it?.
        /// </summary>
        internal static string searchPublishHouseFailed {
            get {
                return ResourceManager.GetString("searchPublishHouseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set inventory code for book.
        /// </summary>
        internal static string setBookNum {
            get {
                return ResourceManager.GetString("setBookNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string showInfo {
            get {
                return ResourceManager.GetString("showInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name of user that you want to find.
        /// </summary>
        internal static string statusStripAdminMain {
            get {
                return ResourceManager.GetString("statusStripAdminMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user in system. Fill all fields that mark with *.
        /// </summary>
        internal static string statusStripControlAdmin {
            get {
                return ResourceManager.GetString("statusStripControlAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on and start work with system.
        /// </summary>
        internal static string statusStripLogOn {
            get {
                return ResourceManager.GetString("statusStripLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type title of book that you want to find.
        /// </summary>
        internal static string statusStripStockmanMain {
            get {
                return ResourceManager.GetString("statusStripStockmanMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stockman.
        /// </summary>
        internal static string stockman {
            get {
                return ResourceManager.GetString("stockman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stockman control window.
        /// </summary>
        internal static string stockmanWelcome {
            get {
                return ResourceManager.GetString("stockmanWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull.
        /// </summary>
        internal static string successfull {
            get {
                return ResourceManager.GetString("successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your login for log on to library system.
        /// </summary>
        internal static string tipsLogin {
            get {
                return ResourceManager.GetString("tipsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password for log on to library system.
        /// </summary>
        internal static string tipsPassword {
            get {
                return ResourceManager.GetString("tipsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not register yet.
        /// </summary>
        internal static string userDeleteFailed {
            get {
                return ResourceManager.GetString("userDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        internal static string userInfo {
            get {
                return ResourceManager.GetString("userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;User&quot; should not be empty.
        /// </summary>
        internal static string userSearchEmpty {
            get {
                return ResourceManager.GetString("userSearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not exist in system. You can create it!.
        /// </summary>
        internal static string userSearchFailed {
            get {
                return ResourceManager.GetString("userSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String for search user is not valid.
        /// </summary>
        internal static string userSearchNull {
            get {
                return ResourceManager.GetString("userSearchNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to library managment system.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
